# -*- coding: utf-8 -*-
"""職稱分類_暴力法.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_uWYqw0CTTIcX2zbE6T8ikE3LmydY-rC
"""

#人工暴力分類
#在function中丟入中文/英文職稱名以後，print出該職稱的分類種類(1~4等第)
def category_function(original_job):
  
  #人工分類分為這幾類
  #等第四：高收入族群，公司經營管理階層
  #等第三：一般工作，平均值
  #等第二：非正職工作或工作不穩定，收入平均為最低時薪收入平均為最低時薪
  #等第一：完全沒有工作、收入零
  
  highest_reputation_job_title = ["總經理", "老闆", "老板", "董事長", "董事", "總裁", "CEO", "合夥人", "執行長"]
  high_reputation_job_title = ["律師", "老師", "Manager", "教授", "藥師", "法官", "公務人員","上尉", "少校", "少尉",
                             "警察", "教師", "醫生", "醫師", "導師", "獸醫", "財務長", "CFO", "工程師", "engineer",
                             "Engineer", "主管", "助理", "特助", "秘書", "Assistant"]
  low_reputation_job_title = ["實習", "學徒", "工讀生", "工讀", "助工", "派遣", "兼職", "兼差", "工友", "打雜", 
                            "服務生","服務員", "掃地", "打工", "臨工", "工人", "粗工", "清潔", "練習生", "臨時"]
  lowest_reputation_job_title = ["無", "nan", "無業", "待業", "沒有", "學生", "爸爸", "媽媽", "學系", "哥", "家管",
                               "家事管理", "家庭主婦", "家事", "家庭"]

  job_title_i = str(original_job)
  job_title_i = job_title_i.strip()
  contain_category = []
  if job_title_i == "" or any([n in job_title_i for n in lowest_reputation_job_title]) == True or job_title_i == "家" or all([n in job_title_i for n in ["?", " ", ",", "."]]) == True:
      print(1)
  else:
    #先看看職稱裡有哪些類別的關鍵字，不直接歸類是因為會有是因為會有ex：助理教授、總經理特助問題
      if any([e in job_title_i for e in low_reputation_job_title]) == True:
        contain_category.append(str(2))
      if any([e in job_title_i for e in high_reputation_job_title]) == True:
        contain_category.append(str(3))
      if any([e in job_title_i for e in highest_reputation_job_title]) == True:
        contain_category.append(str(4))

      if all([n in contain_category for n in ["2"]]) == True:
        print(2)
      elif all([n in contain_category for n in ["3"]]) == True:
        print(3)
      elif any([n in contain_category for n in ["4"]]) == True:
        print(4)

      elif contain_category == []:
        print(3)

      else:
        max_index = 0
        beling_to_catagory = -1
        for k in range(2, 5):
          k = str(k)
          if contain_category.find(k) >= 0 and contain_category.find(k) > max_index:
            max_index = contain_category.find(k)
            beling_to_catagory = int(k)
        print(beling_to_catagory)